version: '3.8'

services:
    app:
        build: .
        container_name: news-aggregator
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
            - ./docker-resources/utils/php.ini/php.ini:/usr/local/etc/php/php.ini:ro
        depends_on:
            db:
                condition: service_healthy
        networks:
            - news_app_network

    webserver:
        image: nginx:alpine
        container_name: news_app_nginx
        restart: unless-stopped
        ports:
            - "7001:80"
        volumes:
            - .:/var/www/html
            - ./docker-resources/utils/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - news_app_network

    db:
        image: mysql:8.0
        container_name: news_app_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: news-aggregator
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker-resources/utils/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - news_app_network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: news_app_phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 10G
        restart: unless-stopped
        ports:
            - "8082:80"
        networks:
            - news_app_network

volumes:
    db_data:

networks:
    news_app_network:
        driver: bridge
